# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.openXVideoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openXVideoBtn.setGeometry(QtCore.QRect(10, 230, 151, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.openXVideoBtn.setFont(font)
        self.openXVideoBtn.setObjectName("openXVideoBtn")
        self.openCameraBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openCameraBtn.setEnabled(False)
        self.openCameraBtn.setGeometry(QtCore.QRect(10, 280, 151, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.openCameraBtn.setFont(font)
        self.openCameraBtn.setObjectName("openCameraBtn")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(638, 10, 16, 371))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(190, 380, 891, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(10, 560, 1080, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.video2_title = QtWidgets.QLabel(self.centralwidget)
        self.video2_title.setGeometry(QtCore.QRect(770, 10, 200, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.video2_title.setFont(font)
        self.video2_title.setObjectName("video2_title")
        self.video1 = QtWidgets.QLabel(self.centralwidget)
        self.video1.setGeometry(QtCore.QRect(198, 40, 431, 341))
        self.video1.setMinimumSize(QtCore.QSize(400, 330))
        self.video1.setFrameShape(QtWidgets.QFrame.Panel)
        self.video1.setText("")
        self.video1.setAlignment(QtCore.Qt.AlignCenter)
        self.video1.setObjectName("video1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 151, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.exitBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exitBtn.setGeometry(QtCore.QRect(10, 140, 151, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.exitBtn.setFont(font)
        self.exitBtn.setObjectName("exitBtn")
        self.openSamleDeviceBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openSamleDeviceBtn.setEnabled(False)
        self.openSamleDeviceBtn.setGeometry(QtCore.QRect(10, 40, 151, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.openSamleDeviceBtn.setFont(font)
        self.openSamleDeviceBtn.setObjectName("openSamleDeviceBtn")
        self.output_msg = QtWidgets.QTextEdit(self.centralwidget)
        self.output_msg.setGeometry(QtCore.QRect(198, 400, 891, 151))
        self.output_msg.setObjectName("output_msg")
        self.video2 = QtWidgets.QLabel(self.centralwidget)
        self.video2.setGeometry(QtCore.QRect(658, 40, 431, 341))
        self.video2.setMinimumSize(QtCore.QSize(400, 330))
        self.video2.setFrameShape(QtWidgets.QFrame.Panel)
        self.video2.setText("")
        self.video2.setAlignment(QtCore.Qt.AlignCenter)
        self.video2.setObjectName("video2")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(170, 10, 21, 551))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(10, 180, 151, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(10, 370, 151, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 390, 121, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 200, 121, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.openVideo2Btn = QtWidgets.QPushButton(self.centralwidget)
        self.openVideo2Btn.setEnabled(True)
        self.openVideo2Btn.setGeometry(QtCore.QRect(10, 470, 151, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.openVideo2Btn.setFont(font)
        self.openVideo2Btn.setObjectName("openVideo2Btn")
        self.openVideo1Btn = QtWidgets.QPushButton(self.centralwidget)
        self.openVideo1Btn.setGeometry(QtCore.QRect(10, 420, 151, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.openVideo1Btn.setFont(font)
        self.openVideo1Btn.setObjectName("openVideo1Btn")
        self.openVideoFolderBtn = QtWidgets.QPushButton(self.centralwidget)
        self.openVideoFolderBtn.setGeometry(QtCore.QRect(10, 90, 151, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.openVideoFolderBtn.setFont(font)
        self.openVideoFolderBtn.setObjectName("openVideoFolderBtn")
        self.video1_title = QtWidgets.QLabel(self.centralwidget)
        self.video1_title.setGeometry(QtCore.QRect(338, 10, 171, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.video1_title.setFont(font)
        self.video1_title.setObjectName("video1_title")
        self.gaitCompareBtn = QtWidgets.QPushButton(self.centralwidget)
        self.gaitCompareBtn.setEnabled(True)
        self.gaitCompareBtn.setGeometry(QtCore.QRect(10, 520, 151, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.gaitCompareBtn.setFont(font)
        self.gaitCompareBtn.setObjectName("gaitCompareBtn")
        self.gaitRecognizeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.gaitRecognizeBtn.setEnabled(True)
        self.gaitRecognizeBtn.setGeometry(QtCore.QRect(10, 330, 151, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.gaitRecognizeBtn.setFont(font)
        self.gaitRecognizeBtn.setObjectName("gaitRecognizeBtn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.openXVideoBtn.setText(_translate("MainWindow", "打开待识别视频"))
        self.openCameraBtn.setText(_translate("MainWindow", "打开摄像头"))
        self.video2_title.setText(_translate("MainWindow", "视频2"))
        self.label_2.setText(_translate("MainWindow", "步态视频分类归档"))
        self.exitBtn.setText(_translate("MainWindow", "开始归档"))
        self.openSamleDeviceBtn.setText(_translate("MainWindow", "打开采集装置"))
        self.label_4.setText(_translate("MainWindow", "步态鉴别"))
        self.label_5.setText(_translate("MainWindow", "步态识别/检索"))
        self.openVideo2Btn.setText(_translate("MainWindow", "打开视频文件2"))
        self.openVideo1Btn.setText(_translate("MainWindow", "打开视频文件1"))
        self.openVideoFolderBtn.setText(_translate("MainWindow", "选择视频文件夹"))
        self.video1_title.setText(_translate("MainWindow", "视频1"))
        self.gaitCompareBtn.setText(_translate("MainWindow", "开始鉴别"))
        self.gaitRecognizeBtn.setText(_translate("MainWindow", "开始识别"))

